# Generated by Django 5.0.1 on 2024-01-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appstore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
